import '@/styles/globals.css'
import { AuthContextProvider } from '@/context/AuthContext';
import Head from 'next/head';
import '@/styles/marker.css'
import { library } from '@fortawesome/fontawesome-svg-core'
import { faBuilding, faStar, faUser, faDollar } from '@fortawesome/free-solid-svg-icons'
import { SavedRoutesContextProvider } from '@/context/SavedRouteContext';



export default function App({ Component, pageProps }) {
  library.add(faBuilding, faStar, faUser, faDollar)
  return (
    <>
      <Head>
        <title>Routourist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AuthContextProvider>
        <SavedRoutesContextProvider>
          <Component {...pageProps} />
        </SavedRoutesContextProvider>
      </AuthContextProvider>
    </>
  )
}
