import Head from 'next/head'
import Image from 'next/image'
import PlayArrowRoundedIcon from '@mui/icons-material/PlayArrowRounded';


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <div className='bg-eggshell w-full h-full' >
         <div className='w-screen h-screend'>
          <button className='rounded-full w-10 h-10 bg-green text-gray shadow-md  '><PlayArrowRoundedIcon></PlayArrowRoundedIcon></button>
            <div className='grid grid-cols-8 grid-rows-2 gap-1 w-screen h-screen'>

              <div className='col-span-6 justify-self-auto self-center w-full row-span-1'>
                <div className='h-10'></div>
                <h1 className='ml-8 font-titlefont font-black laptop:text-7xl tablet:text-xl'>Navigating just got <span className='bg-green'>simpler.</span></h1>
              </div>
              <div className='col-span-2 justify-self-start self-center row-span-1'>
                <p>image example</p>
              </div>
              

              

              <div className='col-span-6 row-span-1'>
                <div className='ml-8'>examples</div>
              </div>
              <div className='col-span-2 row-span-1 justify-center'>
                <button className='font-medium font-bodyfont rounded-full w-20 h-10 bg-green text-gray shadow-md self-center'>sign up</button>
                <button className='font-medium font-bodyfont rounded-full w-20 h-10 bg-green text-gray ml-4 shadow-md self-center'>login</button>
              </div>
            </div>
          </div>

        <div className='w-screen h-screen'>
          
        </div>
        
      </div>
        
    </>
  )
}
